config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#root'

  resources :posts, only: [:create, :new]
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	validates :content, :presence => true
	
	default_scope -> {order(created_at: :desc)}
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:create]
	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			flash[:success] = 'Post Success!'
			redirect_to root_path
		else
			flash[:error] = 'Something went wrong'
			render :new
		end
	end

	def new
		@post = Post.new
	end

	private

		def post_params
			params.require(:post).permit(:content)
		end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def root
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <div class="logo"><%= link_to 'Derp', root_path %></div>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">Menu</a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
        <% if user_signed_in? %>
          <li class="nav-link"><%= link_to "New", new_post_path %></li>
          <li class="nav-link"><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
        <% else %>
          <li class="nav-link"><%= link_to "Sign In", new_user_session_path %></li>
          <li class="nav-link"><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Meidum Clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 	
	<%= render 'layouts/header' %>

	<div class="container">
		<% flash.each do |message_type, message| %>
			<div id="flash" class="flash-<%= message_type %>"><%= message %></div>
		<% end %>

		<%= yield %>
	</div>

</body>
</html>

app/views/posts/new.html.erb
<div class="form-bigbox">
  <div class="form-box">
		<%= form_for :post, url: posts_path do |f| %>
		    <%= f.text_area :content, placeholder: "Content", class: 'form-control' %>
		    <br>
		    <div class="actions">
			  	<%= f.submit "Submit" %>
			  </div>

		<% end %>
	</div>
</div>

app/views/static_pages/root.html.erb
<h1>hello</h1>